sever:
  port: 8080

spring:
  application:
    name: CLOUD-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MohammadAbdoulAzizCiss/cloud-config
          clone-on-start: true
